### ISSUE TITLE
Figure tweaks

### ISSUE THREAD

**Issue by ndattani** [HPQC-LABS/Pegasus#14]
Maybe try to make horizontal lines match? 

![selection_999 628](https://user-images.githubusercontent.com/1163013/49324253-369b1500-f4f8-11e8-90b8-f899f979d544.png)

**Comment by ndattani** [comment]
Shouldn't this be: green orange orange green, NOT, orange orange green green ?
![selection_999 629](https://user-images.githubusercontent.com/1163013/49324336-98a84a00-f4f9-11e8-8444-5c6f3a36e3ff.png)

**Comment by ndattani** [comment]
Making these closer will help to make green and red edges to be of similar size. Then we don't have to explain why pegasus edges seem to be so asymmetric

![selection_999 630](https://user-images.githubusercontent.com/1163013/49324386-5a5f5a80-f4fa-11e8-87f2-a62eefe85df2.png)

**Comment by szilardszalay** [comment]
> Shouldn't this be: green orange orange green, NOT, orange orange green green ?
> ![selection_999 629](https://user-images.githubusercontent.com/1163013/49324336-98a84a00-f4f9-11e8-8444-5c6f3a36e3ff.png)

Yes, fixed now. (this affects not only the "Dot" figures, but all "full" figures.)

**Comment by szilardszalay** [comment]
> Making these closer will help to make green and red edges to be of similar size. Then we don't have to explain why pegasus edges seem to be so asymmetric
> 
> ![selection_999 630](https://user-images.githubusercontent.com/1163013/49324386-5a5f5a80-f4fa-11e8-87f2-a62eefe85df2.png)

Those larger spacings are intended: help to separate z=2 layer from z=0. Setting all the spacings uniform would be confusing, hiding that there are 3 layers. Take a look at https://github.com/HPQC-LABS/Pegasus/blob/figures2/metapostfigs/fig_PegasusDotTilt5x5full.pdf , it is like a 3D figure, the aligned unit cells (same (x,y) coordinates but different z) give the "depth".

**Comment by szilardszalay** [comment]
> Maybe try to make horizontal lines match?
> 
> ![selection_999 628](https://user-images.githubusercontent.com/1163013/49324253-369b1500-f4f8-11e8-90b8-f899f979d544.png)

Still need more time for this one.

**Comment by ndattani** [comment]
> Yes, fixed now. (this affects not only the "Dot" figures, but all "full" figures.)

So it  was an even more important change than I thought.

> Those larger spacings are intended: help to separate z=2 layer from z=0. Setting all the spacings uniform would be confusing, hiding that there are 3 layers. 

I fully understand and appreciate that, however there is still a lot of room left for those lines to be moved in (as the yellow arrows indicate), and still have a larger gap between z=2 and 0 than between 1 and 2.  Alternatively you can make the gap between z=2 and 0 to be SMALLER than the gap between 1 and 2 (so still there's a difference between the z=0,1,2 separation and the z=2,0 separation... just that the difference is negative rather than positive). 

> Take a look at https://github.com/HPQC-LABS/Pegasus/blob/figures2/metapostfigs/fig_PegasusDotTilt5x5full.pdf , it is like a 3D figure, the aligned unit cells (same (x,y) coordinates but different z) give the "depth".

I see, however in that figure you just sent, the orange and green can DEFINITELY be made the same size, or at least more similar to, the blue/red. This would in fact make room for more cells per cm^2 on the computer screen on paper, so we'd be able to fit more cells in a given amount of space, or stay at 5x5 but with everything magnified much better. In that PDF you just linked, it is also a bit weird that the blue/red lines follow a straight line, then go diagonal, then go straight again, etc.  Maybe having a grey background for the BACK surface of the whole box, would help with this, as we'd be able to see that the blue/red line from z=2 -> 0 is going along the "body diagonal" of a cube, rather than on the "face diagonal" along the back, or the edge of the cube. But also, making green/orange shorter, will help to make the blue/red lines from z=2,0 to have an angle even more different from the z=1->2 lines, and therefore would help to emphasize what's going on at z=2,0.

> Still need more time for this one.

Making those horizontal lines match would make the aesthetics look better, but it's less important than some of the other things.
